on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  tag-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Check for the existence of the comment
        run: gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA -q '("FOUND_COMMIT=\"" + .sha + " " +.commit.message +"\"")' >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          COMMIT_SHA: ${{ inputs.commit_sha }}

      - name: Do the tagging
        if: contains(env.FOUND_COMMIT, env.COMMIT_SHA )
        run: echo "About to tag $COMMIT_SHA with $TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ inputs.commit_sha }}
          TAG: ${{ inputs.tag }}


