on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string
      tag:
        required: true
        type: string
      tag_message:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      repository_owner:
        required: true
        type: string


jobs:
  tag-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OWNER: ${{ inputs.repository_owner }}
      REPO: ${{ inputs.repository_name }}
      COMMIT_SHA: ${{ inputs.commit_sha }}
      TAG: ${{ inputs.tag }}
      TAG_MESSAGE: ${{ inputs.tag_message }}

    steps:
      - name: Check for the existence of the commit
        run: |
          COMMIT_PATH="repos/$OWNER/$REPO/commits/$COMMIT_SHA"
          echo "Checking existence of \"$COMMIT_PATH\""
          gh api "$COMMIT_PATH"  -q '("FOUND_COMMIT=\"" + .sha + " " +.commit.message +"\"")' >> $GITHUB_ENV

      - name: Prepare to tag
        if: contains(env.FOUND_COMMIT, env.COMMIT_SHA )
        run: |
          echo "continue_job=true" >> $GITHUB_ENV
          echo "About to apply tag $TAG to $FOUND_COMMIT"
        env:
          COMMIT_SHA: ${{ inputs.commit_sha }}

      - name: Do the tag
        if: env.continue_job
        run: |
          API_ENDPOINT="repos/$OWNER/$REPO/git/tags"
          REQUEST_BODY=$(cat << EOF
          {
            "owner": "$OWNER",
            "repo": "$REPO",
            "tag": "$TAG",
            "message": "$TAG_MESSAGE",
            "object": "$COMMIT_SHA",
            type"": "commit"
            }
          }

          EOF
          )
          echo "Adding tag for \n$REQUEST_BODY"
          gh api -X POST "$API_ENDPOINT" --body "$REQUEST_BODY"

