on:
  workflow_call:
    inputs:
      commit_sha:
        required: true
        type: string
      tag:
        required: true
        type: string

jobs:
  test-access-to-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Check for the existence of the comment
        run: |
          FOUND_COMMIT=$(gh api repos/$OWNER/$REPO/commits/$COMMIT_SHA -q '(.sha + "\t" +.commit.message)')
          if [ -z "$FOUND_COMMIT"]
          then
              echo "commit_sha $COMMIT_SHA not found in $OWNER/$REPO"
              echo "result=failed" >> $GITHUB_ENV
              exit 1
          fi
          echo "Found $FOUND_COMMIT"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          COMMIT_SHA: ${{ inputs.commit_sha }}
